"""DhanHQ v2 market-data provider.

Implements the documented Dhan REST and WebSocket APIs directly rather than
depending on the ``dhanhq`` SDK - the live feed is a small, fully-specified
binary protocol, and going direct keeps the dependency surface unchanged
(``websockets`` and ``requests`` are already installed).

References (DhanHQ API v2):
  - Instrument ids    : read from data/dhan_instruments.json, generated by
                        scripts/fetch_instrument_master.py - never downloaded here
  - LTP / OHLC        : POST https://api.dhan.co/v2/marketfeed/{ltp,ohlc}
  - Daily candles     : POST https://api.dhan.co/v2/charts/historical
  - Live feed         : wss://api-feed.dhan.co?version=2&token=..&clientId=..&authType=2

Credentials come from the environment. Only ``DHAN_ACCESS_TOKEN`` is required -
Dhan embeds the client id in the token, so ``DHAN_CLIENT_ID`` is an optional
override. Neither is ever logged.
"""

import asyncio
import base64
import json
import logging
import os
import struct
import threading
import time
from datetime import date, datetime, timedelta
from typing import Dict, List, Optional, Tuple

import requests

from market.instruments import load_instruments, regenerate_hint
from market.market_hours import IST, now_ist, todays_session_date
from market.providers.base import (
    SEGMENT_CASH,
    SEGMENT_INDEX,
    DayBar,
    FeedHandle,
    InstrumentRef,
    MarketDataProvider,
)

logger = logging.getLogger(__name__)

REST_BASE = "https://api.dhan.co/v2"
FEED_URL = "wss://api-feed.dhan.co"

# Dhan exchange-segment key for NSE cash equities.
NSE_EQ = "NSE_EQ"
#: Dhan addresses index values as their own exchange segment. Index quotes
#: and the index feed both need the paid Data API plan, same as equities.
IDX_I = "IDX_I"

#: Universe segment -> Dhan exchange segment.
SEGMENT_CODES = {
    SEGMENT_CASH: NSE_EQ,
    SEGMENT_INDEX: IDX_I,
}

#: Universe segment -> Dhan ``instrument`` type, which the historical-candle
#: endpoint requires alongside the exchange segment. Dhan's documented table
#: for that endpoint lists neither IDX_I nor INDEX, but both are what the
#: instrument master uses for index rows; if Dhan rejects them the call simply
#: returns nothing and the index board keeps whatever previous close it had.
INSTRUMENT_CODES = {
    SEGMENT_CASH: "EQUITY",
    SEGMENT_INDEX: "INDEX",
}


def segment_code(segment: str) -> str:
    """Dhan exchange segment for a universe segment, defaulting to cash."""
    return SEGMENT_CODES.get((segment or SEGMENT_CASH).upper(), NSE_EQ)


def instrument_code(segment: str) -> str:
    """Dhan instrument type for a universe segment, defaulting to equity."""
    return INSTRUMENT_CODES.get((segment or SEGMENT_CASH).upper(), "EQUITY")

# Feed request codes (Annexure: Feed Request Code)
REQUEST_SUBSCRIBE_TICKER = 15
#: Quote packets carry the LTP *and* the day's open/high/low/volume in one
#: subscription, so breadth costs no extra REST calls. 50 instruments of
#: 50-byte packets is negligible bandwidth.
REQUEST_SUBSCRIBE_QUOTE = 17
REQUEST_DISCONNECT = 12

# Feed response codes (Annexure: Feed Response Code)
RESPONSE_TICKER = 2
RESPONSE_QUOTE = 4
#: Sent alongside quote packets. Meaningless for cash equities, but it must
#: be stepped over correctly or every following packet in the frame
#: misaligns.
RESPONSE_OI = 5
RESPONSE_PREV_CLOSE = 6
RESPONSE_MARKET_STATUS = 7
RESPONSE_DISCONNECT = 50

# Total packet sizes (header + payload) for the codes we care about. Used to
# validate the length field in the header before advancing the read offset.
PACKET_SIZES = {
    RESPONSE_TICKER: 16,
    RESPONSE_QUOTE: 50,
    RESPONSE_OI: 12,
    RESPONSE_PREV_CLOSE: 16,
    RESPONSE_DISCONNECT: 10,
}

# Dhan limits: 100 instruments per subscribe message, 5000 per connection,
# 1000 per REST quote request, 1 quote request/second.
SUBSCRIBE_BATCH = 100
REST_BATCH = 1000

#: Dhan error code returned when the account has no Data API plan.
DATA_APIS_NOT_SUBSCRIBED = "806"
#: Dhan error code for rate limiting.
RATE_LIMITED = "805"
#: Dhan allows 1 request/second across all market-quote endpoints, so calls to
#: ltp/ohlc/quote share one throttle.
MIN_QUOTE_INTERVAL = 1.1


#: Dhan allows one quote request per second **per client id**, not per
#: connection or per object. The heatmap runs one provider instance per
#: board (equities and indices), so a per-instance throttle would let two
#: boards fire simultaneously and trip error 805. These are module level so
#: every DhanProvider in the process queues behind the same gate.
_QUOTE_GATE = threading.Lock()
_LAST_QUOTE_AT = 0.0


def _quote_gate() -> None:
    """Block until it is safe to issue another quote request."""
    global _LAST_QUOTE_AT
    with _QUOTE_GATE:
        wait = MIN_QUOTE_INTERVAL - (time.monotonic() - _LAST_QUOTE_AT)
        if wait > 0:
            time.sleep(wait)
        _LAST_QUOTE_AT = time.monotonic()


#: Dhan publishes 1 request/second for quote endpoints and 5/second for the
#: wider "Data APIs" bucket, without saying in so many words which bucket
#: /charts/historical falls in. 4/s stays inside the slower reading of that
#: bucket, which puts a 50-symbol universe at ~13s - paid once at startup and
#: only when the market is closed.
MIN_HISTORY_INTERVAL = 0.25

#: Calendar days of daily candles requested when resolving a previous close.
#: Only the last two sessions are used; the rest is slack for weekends and
#: holiday clusters, which no amount of Diwali can stretch past this.
HISTORY_LOOKBACK_DAYS = 20

#: Give up on the whole universe after this many consecutive symbols yield
#: nothing. One empty response is a thin instrument; five in a row is a
#: missing entitlement or an expired token, and firing 45 more doomed
#: requests would only delay startup.
HISTORY_FAILURE_LIMIT = 5

#: The historical endpoint is rate limited separately from the quote
#: endpoints, so it gets its own gate. Module level for the same reason as
#: the quote gate: the limit is per client id, and one process runs a
#: provider instance per board.
_HISTORY_GATE = threading.Lock()
_LAST_HISTORY_AT = 0.0


def _history_gate() -> None:
    """Block until it is safe to issue another historical-data request."""
    global _LAST_HISTORY_AT
    with _HISTORY_GATE:
        wait = MIN_HISTORY_INTERVAL - (time.monotonic() - _LAST_HISTORY_AT)
        if wait > 0:
            time.sleep(wait)
        _LAST_HISTORY_AT = time.monotonic()


def _candle_dates(stamps) -> List[Optional[date]]:
    """IST dates for a candle series' epoch timestamps, None where unreadable."""
    dates: List[Optional[date]] = []
    for stamp in stamps or []:
        try:
            dates.append(datetime.fromtimestamp(int(stamp), IST).date())
        except (TypeError, ValueError, OSError, OverflowError):
            dates.append(None)
    return dates


def prior_close_from_candles(payload: dict, session_date: Optional[date] = None):
    """The previous session's close from a daily-candle response.

    ``payload`` is Dhan's parallel-array format: ``{"close": [...],
    "timestamp": [...], ...}`` in ascending date order.

    ``session_date`` is the date the *current price* belongs to, or None when
    that price comes from a session earlier than today (weekend, or before
    today's open). This is the whole subtlety:

    - Given a session date, the answer is the last candle strictly *before*
      it. That is correct whether or not today's own candle has been written
      yet - after 15:30 it steps over today, and in the gap before Dhan
      publishes today's candle it still lands on the right day.
    - Without one, the most recent candle *is* the session the current price
      came from, so the answer is the candle before it.

    Returns None rather than guessing when the series is too short or the
    close is not a usable price.
    """
    if not isinstance(payload, dict):
        return None
    closes = payload.get("close") or []
    if len(closes) < 2:
        return None

    dates = _candle_dates(payload.get("timestamp"))
    readable = any(day is not None for day in dates)
    if session_date is not None and readable and len(dates) == len(closes):
        for close, day in zip(reversed(closes), reversed(dates)):
            if day is not None and day < session_date:
                return _positive(close)
        return None

    # No session date, or timestamps we cannot read: treat the last candle as
    # the current session and take the one before it.
    return _positive(closes[-2])


def _positive(value) -> Optional[float]:
    """``value`` as a float when it is a usable price, otherwise None.

    Dhan sends 0 for any field it has no value for yet. Zero must stay
    "unknown" rather than becoming a price.
    """
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if number > 0 else None


def client_id_from_token(access_token: str) -> str:
    """Extract ``dhanClientId`` from a Dhan access token.

    Dhan's JWT carries the client id in its payload, so the dashboard needs
    only the access token. Returns "" if it cannot be read - the caller then
    falls back to an explicitly configured DHAN_CLIENT_ID.

    The token is only decoded, never verified (we are not the issuer) and
    never logged.
    """
    try:
        payload = (access_token or "").split(".")[1]
        payload += "=" * (-len(payload) % 4)
        claims = json.loads(base64.urlsafe_b64decode(payload))
        return str(claims.get("dhanClientId") or "").strip()
    except Exception:
        return ""


def token_expiry(access_token: str) -> Optional[int]:
    """Unix expiry of a Dhan access token, or None if unreadable."""
    try:
        payload = (access_token or "").split(".")[1]
        payload += "=" * (-len(payload) % 4)
        claims = json.loads(base64.urlsafe_b64decode(payload))
        expiry = claims.get("exp")
        return int(expiry) if expiry is not None else None
    except Exception:
        return None


class DhanFeedHandle(FeedHandle):
    """One Dhan market-feed websocket, driven on its own daemon thread.

    The socket runs an asyncio loop in a background thread and writes into
    plain dicts guarded by a lock; ``latest_prices()`` just copies them, so the
    caller never touches asyncio.
    """

    def __init__(self, access_token: str, client_id: str, refs: List[InstrumentRef]):
        self._token = access_token
        self._client_id = client_id
        self._refs = list(refs)
        self._by_id: Dict[int, str] = {}
        for ref in self._refs:
            try:
                self._by_id[int(ref.provider_id)] = ref.symbol
            except (TypeError, ValueError):
                logger.warning("Dhan: bad security id %r for %s", ref.provider_id, ref.symbol)

        self._lock = threading.Lock()
        self._prices: Dict[str, float] = {}
        self._prev_closes: Dict[str, float] = {}
        self._bars: Dict[str, DayBar] = {}

        self._stop = threading.Event()
        self._ready = threading.Event()
        self._error: Optional[BaseException] = None
        self._alive = False
        self._logged_first_packet = False
        self._thread = threading.Thread(
            target=self._run, name="dhan-feed", daemon=True
        )

    # -- lifecycle ------------------------------------------------------
    def start(self, timeout: float = 20.0) -> "DhanFeedHandle":
        """Start the socket and block until subscribed (or raise)."""
        self._thread.start()
        if not self._ready.wait(timeout):
            self.close()
            raise TimeoutError(
                f"Dhan feed did not connect within {timeout:.0f}s"
            )
        if self._error is not None:
            raise self._error
        return self

    @property
    def is_alive(self) -> bool:
        return self._alive and self._thread.is_alive() and not self._stop.is_set()

    def latest_prices(self) -> Dict[str, float]:
        with self._lock:
            return dict(self._prices)

    def previous_closes(self) -> Dict[str, float]:
        with self._lock:
            return dict(self._prev_closes)

    def day_bars(self) -> Dict[str, DayBar]:
        with self._lock:
            return dict(self._bars)

    def close(self) -> None:
        self._stop.set()
        self._alive = False

    # -- socket ---------------------------------------------------------
    def _run(self) -> None:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            loop.run_until_complete(self._main())
        except BaseException as e:  # noqa: BLE001 - surfaced via start()/is_alive
            self._error = e
            logger.warning("Dhan feed stopped: %s: %s", type(e).__name__, e)
        finally:
            self._alive = False
            self._ready.set()
            try:
                loop.close()
            except Exception:
                pass

    async def _main(self) -> None:
        import websockets

        url = (
            f"{FEED_URL}?version=2&token={self._token}"
            f"&clientId={self._client_id}&authType=2"
        )
        # Dhan pings every 10s and drops the connection after 40s of silence;
        # the library answers pings automatically.
        async with websockets.connect(
            url, ping_interval=None, close_timeout=5, max_size=None
        ) as ws:
            await self._subscribe(ws)
            self._alive = True
            self._ready.set()
            logger.info(
                "Dhan feed connected - subscribed to %d instruments", len(self._by_id)
            )
            while not self._stop.is_set():
                try:
                    message = await asyncio.wait_for(ws.recv(), timeout=1.0)
                except asyncio.TimeoutError:
                    continue
                if isinstance(message, bytes):
                    self._parse(message)
            try:
                await ws.send('{"RequestCode": %d}' % REQUEST_DISCONNECT)
            except Exception:
                pass

    async def _subscribe(self, ws) -> None:
        for i in range(0, len(self._refs), SUBSCRIBE_BATCH):
            batch = self._refs[i : i + SUBSCRIBE_BATCH]
            await ws.send(
                json.dumps(
                    {
                        "RequestCode": REQUEST_SUBSCRIBE_QUOTE,
                        "InstrumentCount": len(batch),
                        "InstrumentList": [
                            {
                                "ExchangeSegment": segment_code(r.segment),
                                "SecurityId": str(r.provider_id),
                            }
                            for r in batch
                        ],
                    }
                )
            )

    # -- binary parsing -------------------------------------------------
    def _parse(self, data: bytes) -> None:
        """Decode one websocket frame, which may hold several packets.

        Header (8 bytes, little endian): code:uint8, length:int16,
        segment:uint8, security_id:int32.
        """
        offset, size = 0, len(data)
        prices: Dict[str, float] = {}
        prev: Dict[str, float] = {}
        bars: Dict[str, DayBar] = {}

        while offset + 8 <= size:
            code, length, _segment, security_id = struct.unpack_from(
                "<BHBi", data, offset
            )

            if not self._logged_first_packet:
                self._logged_first_packet = True
                logger.debug(
                    "Dhan first packet: code=%s length=%s security_id=%s frame=%s bytes",
                    code, length, security_id, size,
                )

            # Trust the documented size where we know it; the length field is
            # only used for packets we do not decode.
            step = PACKET_SIZES.get(code, length)
            if step < 8 or offset + step > size:
                step = length if 8 <= length <= size - offset else 0
                if step == 0:
                    break

            symbol = self._by_id.get(security_id)
            if symbol is not None:
                if code == RESPONSE_TICKER and offset + 16 <= size:
                    ltp, _ltt = struct.unpack_from("<fi", data, offset + 8)
                    if ltp > 0:
                        prices[symbol] = float(ltp)
                elif code == RESPONSE_QUOTE and offset + 50 <= size:
                    # f LTP | h qty | i ltt | f atp | i volume | i sellQty |
                    # i buyQty | f open | f close | f high | f low
                    (
                        ltp,
                        _qty,
                        _ltt,
                        _atp,
                        volume,
                        _sell_qty,
                        _buy_qty,
                        day_open,
                        _day_close,
                        day_high,
                        day_low,
                    ) = struct.unpack_from("<fhifiiiffff", data, offset + 8)
                    if ltp > 0:
                        prices[symbol] = float(ltp)
                    # Dhan sends zeros for fields it has no value for yet
                    # (before the session's first trade). Those stay
                    # "unknown": a 0.00 low would put every stock at the
                    # top of its day range.
                    bars[symbol] = DayBar(
                        open=_positive(day_open),
                        high=_positive(day_high),
                        low=_positive(day_low),
                        volume=int(volume) if volume > 0 else None,
                    )
                elif code == RESPONSE_PREV_CLOSE and offset + 16 <= size:
                    close, _oi = struct.unpack_from("<fi", data, offset + 8)
                    if close > 0:
                        prev[symbol] = float(close)
            elif code == RESPONSE_DISCONNECT:
                reason = (
                    struct.unpack_from("<H", data, offset + 8)[0]
                    if offset + 10 <= size
                    else -1
                )
                logger.warning("Dhan feed sent disconnect packet, reason code %s", reason)
                self._alive = False
                self._stop.set()
                return

            offset += step

        if prices or prev or bars:
            with self._lock:
                self._prices.update(prices)
                self._prev_closes.update(prev)
                self._bars.update(bars)


class DhanProvider(MarketDataProvider):
    """DhanHQ v2 provider: instrument master, REST snapshots, live feed."""

    name = "dhan"
    label = "Dhan"

    def __init__(
        self,
        access_token: Optional[str] = None,
        client_id: Optional[str] = None,
        timeout: int = 15,
    ):
        self._token = (access_token or os.getenv("DHAN_ACCESS_TOKEN") or "").strip()
        self._client_id = self._resolve_client_id(
            client_id or os.getenv("DHAN_CLIENT_ID")
        )
        self._timeout = timeout
        # The generated instrument-id file, loaded lazily and kept for the
        # life of the provider. No download, no pandas.
        self._instrument_file = None
        # Quote throttling is shared process-wide (see _quote_gate below):
        # Dhan rate limits per client id, and this dashboard runs one
        # provider instance per board.

    def _throttle_quotes(self) -> None:
        """Stay under Dhan's quote rate limit.

        Delegates to the process-wide gate: the limit applies to the client
        id, and every board in this process shares one.
        """
        _quote_gate()

    def _resolve_client_id(self, configured: Optional[str]) -> str:
        """Client id from the token, which is authoritative.

        Dhan embeds ``dhanClientId`` in the access token, so DHAN_CLIENT_ID is
        optional. A configured value is only used when the token has none, and
        an obvious placeholder is ignored outright - a stale
        ``DHAN_CLIENT_ID=your_dhan_client_id`` left in .env would otherwise turn
        a clear "Data APIs not subscribed" error into a confusing auth failure.
        """
        configured = (configured or "").strip()
        if configured and (
            configured.lower().startswith(("your_", "<", "xxx")) or not configured.isdigit()
        ):
            logger.warning(
                "Ignoring placeholder DHAN_CLIENT_ID=%r - reading the client id "
                "from the access token instead",
                configured,
            )
            configured = ""

        from_token = client_id_from_token(self._token)
        if from_token:
            if configured and configured != from_token:
                logger.warning(
                    "DHAN_CLIENT_ID does not match the access token's client id; "
                    "using the token's value"
                )
            return from_token
        return configured

    # -- config / auth --------------------------------------------------
    def is_configured(self) -> bool:
        return bool(self._token and self._client_id)

    def _headers(self) -> Dict[str, str]:
        return {
            "access-token": self._token,
            "client-id": self._client_id,
            "Accept": "application/json",
            "Content-Type": "application/json",
        }

    def connect(self) -> None:
        if not self.is_configured():
            raise RuntimeError(
                "Dhan credentials missing - set DHAN_ACCESS_TOKEN "
                "(DHAN_CLIENT_ID is optional; it is read from the token)"
            )
        expiry = token_expiry(self._token)
        if expiry is not None:
            remaining = expiry - int(time.time())
            if remaining <= 0:
                raise RuntimeError(
                    "Dhan access token has expired - generate a new one"
                )
            logger.info("Dhan access token valid for %.1f more hours", remaining / 3600)
        # /profile is a non-trading endpoint: it validates the token even when
        # the Data API plan is inactive, so it gives a precise diagnosis.
        profile = self._json(
            requests.get(
                f"{REST_BASE}/profile", headers=self._headers(), timeout=self._timeout
            )
        )
        error = self._error_of(profile)
        if error or not profile.get("dhanClientId"):
            code, message = error or ("", "token rejected")
            raise RuntimeError(f"Dhan authentication failed: {code} {message}".strip())

        data_plan = str(profile.get("dataPlan", "")).strip()
        logger.info(
            "Dhan authenticated (client %s..., data plan: %s, token valid to %s)",
            self._client_id[:4],
            data_plan or "unknown",
            profile.get("tokenValidity", "?"),
        )

        # Market data - REST and the live feed alike - needs the Data API plan.
        # This probe goes through the same throttle as every other quote call:
        # it is a quote request, and two boards starting together would
        # otherwise collide here and fail activation with a spurious 805.
        error = None
        for attempt in range(2):
            self._throttle_quotes()
            resp = requests.post(
                f"{REST_BASE}/marketfeed/ltp",
                headers=self._headers(),
                json={NSE_EQ: [1333]},
                timeout=self._timeout,
            )
            error = self._error_of(self._json(resp))
            if error is None or error[0] != RATE_LIMITED:
                break
            if attempt == 0:
                logger.debug("Dhan probe rate limited - retrying")
                time.sleep(MIN_QUOTE_INTERVAL)

        if error:
            code, message = error
            if code == DATA_APIS_NOT_SUBSCRIBED or "not subscribed" in message.lower():
                raise RuntimeError(
                    "Dhan Data API plan is not active on this account "
                    f"(dataPlan={data_plan or 'Deactive'}, error {code}: {message}). "
                    "Market quotes and the live feed both require it - subscribe "
                    "under Dhan -> Profile -> DhanHQ Trading APIs -> Data APIs."
                )
            raise RuntimeError(f"Dhan market data unavailable: {code} {message}")
        resp.raise_for_status()

    @staticmethod
    def _json(resp) -> dict:
        try:
            data = resp.json()
        except ValueError:
            return {}
        return data if isinstance(data, dict) else {}

    @staticmethod
    def _error_of(payload: dict):
        """Return (code, message) for a Dhan error body, or None if it is not one.

        Dhan reports failures as ``{"status": "failed", "data": {"806": "..."}}``
        with the key casing varying between "data" and "Data", and elsewhere as
        ``{"status": "failure", "errorCode": ..., "errorMessage": ...}``.
        """
        if not isinstance(payload, dict):
            return None
        status = str(payload.get("status", "")).lower()
        if status not in ("failed", "failure"):
            return None
        if payload.get("errorCode") or payload.get("errorMessage"):
            return str(payload.get("errorCode") or ""), str(payload.get("errorMessage") or "")
        block = payload.get("data") or payload.get("Data") or {}
        if isinstance(block, dict) and block:
            code, message = next(iter(block.items()))
            return str(code), str(message)
        return "", "unknown Dhan error"

    # -- reference data -------------------------------------------------
    def _instrument_set(self):
        """The generated instrument-id file, read once per provider.

        Deliberately not a download. Dhan publishes ids only as a 35 MB
        uncompressed CSV of every F&O contract on every exchange; fetching it
        at startup cost 15-40 s per board for sixty numbers that change when
        NSE reconstitutes an index, not when the dashboard boots. The file is
        generated offline by ``scripts/fetch_instrument_master.py`` - see
        ``market/instruments.py``.
        """
        if self._instrument_file is None:
            self._instrument_file = load_instruments()
            if self._instrument_file.is_usable:
                logger.info("Dhan instruments: %s", self._instrument_file.describe())
        return self._instrument_file

    def resolve_instruments(
        self, symbols: List[str], segment: str = SEGMENT_CASH
    ) -> Tuple[Dict[str, InstrumentRef], List[str]]:
        resolved: Dict[str, InstrumentRef] = {}
        missing: List[str] = []
        if not symbols:
            return resolved, missing

        segment = (segment or SEGMENT_CASH).upper()
        available = self._instrument_set()
        if not available.is_usable:
            logger.error("Dhan instrument ids unavailable: %s", available.error)
            return resolved, list(symbols)

        lookup = available.security_ids(segment)
        for symbol in symbols:
            security_id = lookup.get(symbol)
            if not security_id:
                logger.warning(
                    "Dhan: %s (%s) is not in %s", symbol, segment, available.path
                )
                missing.append(symbol)
                continue
            resolved[symbol] = InstrumentRef(
                symbol=symbol, provider_id=security_id, segment=segment
            )

        logger.info(
            "Dhan resolved %d/%d instruments (%s)", len(resolved), len(symbols), segment
        )
        if missing:
            logger.warning(
                "%d symbol(s) missing from %s. %s",
                len(missing),
                available.path,
                regenerate_hint(available.path),
            )
        return resolved, missing

    def _post_marketfeed(self, endpoint: str, refs: List[InstrumentRef]) -> dict:
        """Batched quote call, grouped by exchange segment.

        Returns ``{security_id: entry}`` merged across segments. Ids are
        unique within a segment but *not* across them (index id 13 and an
        equity id 13 can both exist), so callers must only pass refs from one
        universe - which they do, since each board has its own service.
        """
        by_segment: Dict[str, List[int]] = {}
        for ref in refs:
            try:
                by_segment.setdefault(segment_code(ref.segment), []).append(
                    int(ref.provider_id)
                )
            except (TypeError, ValueError):
                continue
        if not by_segment:
            return {}

        merged: dict = {}
        for code, ids in by_segment.items():
            for i in range(0, len(ids), REST_BATCH):
                chunk = ids[i : i + REST_BATCH]
                payload, error = {}, None
                # One retry: a 805 usually just means we were a little quick.
                for attempt in range(2):
                    self._throttle_quotes()
                    resp = requests.post(
                        f"{REST_BASE}/marketfeed/{endpoint}",
                        headers=self._headers(),
                        json={code: chunk},
                        timeout=self._timeout,
                    )
                    payload = self._json(resp)
                    error = self._error_of(payload)
                    if error is None or error[0] != RATE_LIMITED:
                        break
                    if attempt == 0:
                        logger.debug("Dhan %s rate limited - retrying", endpoint)
                        time.sleep(MIN_QUOTE_INTERVAL)
                if error:
                    logger.warning("Dhan %s error: %s %s", endpoint, *error)
                    continue
                section = (payload.get("data") or {}).get(code) or {}
                merged.update(section)
        return merged

    def _by_symbol(
        self, refs: List[InstrumentRef], raw: dict, extract
    ) -> Dict[str, float]:
        by_id = {str(r.provider_id): r.symbol for r in refs}
        out: Dict[str, float] = {}
        for security_id, entry in (raw or {}).items():
            symbol = by_id.get(str(security_id))
            if symbol is None:
                continue
            try:
                value = extract(entry)
            except (TypeError, ValueError, AttributeError):
                continue
            if value and value > 0:
                out[symbol] = float(value)
        return out

    def get_previous_close(self, refs: List[InstrumentRef]) -> Dict[str, float]:
        """Previous-day close from the OHLC endpoint.

        Dhan's OHLC block reports the previous session's close **while the
        market is open**. After the close it reports today's close instead, so
        callers outside the session want ``get_prior_session_close`` - see the
        base class. Anything non-positive is treated as missing, and the feed's
        explicit previous-close packet fills the gaps.
        """
        raw = self._post_marketfeed("ohlc", refs)
        closes = self._by_symbol(
            refs, raw, lambda e: (e.get("ohlc") or {}).get("close")
        )
        logger.info("Dhan resolved previous close for %d/%d", len(closes), len(refs))
        return closes

    def _post_historical(self, ref: InstrumentRef, window: dict) -> Optional[dict]:
        """Daily candles for one instrument, or None if the call gave nothing.

        Unlike the quote endpoints this one takes a single security per
        request, so a universe costs one call per symbol. It is only ever used
        for reference data at startup, never per tick.
        """
        try:
            security_id = str(int(ref.provider_id))
        except (TypeError, ValueError):
            return None

        body = {
            "securityId": security_id,
            "exchangeSegment": segment_code(ref.segment),
            "instrument": instrument_code(ref.segment),
            **window,
        }
        for attempt in range(2):
            _history_gate()
            try:
                resp = requests.post(
                    f"{REST_BASE}/charts/historical",
                    headers=self._headers(),
                    json=body,
                    timeout=self._timeout,
                )
            except requests.RequestException as e:
                logger.debug("Dhan historical request failed for %s: %s", ref.symbol, e)
                return None

            payload = self._json(resp)
            error = self._error_of(payload)
            if error is None:
                return payload or None
            if error[0] != RATE_LIMITED:
                logger.debug(
                    "Dhan historical error for %s: %s %s", ref.symbol, *error
                )
                return None
            if attempt == 0:
                time.sleep(MIN_HISTORY_INTERVAL)
        return None

    def get_prior_session_close(self, refs: List[InstrumentRef]) -> Dict[str, float]:
        """Previous close from daily candles, for use outside market hours.

        The OHLC endpoint behind ``get_previous_close`` starts reporting
        *today's* close the moment trading stops, so it cannot answer this
        question after 15:30. Daily candles can.

        One request per symbol, throttled, and abandoned early if the account
        cannot serve them at all. Symbols that yield nothing are simply absent
        from the result: a missing previous close shows as a data gap, which is
        honest, where the OHLC value would show as +0.00%, which is not.
        """
        if not refs:
            return {}

        today = now_ist().date()
        window = {
            # toDate is documented as non-inclusive, so today's own candle
            # only appears if we ask past it.
            "fromDate": (today - timedelta(days=HISTORY_LOOKBACK_DAYS)).isoformat(),
            "toDate": (today + timedelta(days=1)).isoformat(),
        }
        session_date = todays_session_date()

        closes: Dict[str, float] = {}
        consecutive_failures = 0
        for ref in refs:
            payload = self._post_historical(ref, window)
            close = prior_close_from_candles(payload, session_date) if payload else None
            if close:
                closes[ref.symbol] = close
                consecutive_failures = 0
                continue
            consecutive_failures += 1
            if consecutive_failures >= HISTORY_FAILURE_LIMIT:
                logger.warning(
                    "Dhan returned no daily candles for %d symbols in a row - "
                    "abandoning the historical previous-close lookup",
                    consecutive_failures,
                )
                break

        logger.info(
            "Dhan resolved previous close for %d/%d from daily candles",
            len(closes),
            len(refs),
        )
        return closes

    def get_ltp_snapshot(self, refs: List[InstrumentRef]) -> Dict[str, float]:
        raw = self._post_marketfeed("ltp", refs)
        return self._by_symbol(refs, raw, lambda e: e.get("last_price"))

    def get_day_bars(self, refs: List[InstrumentRef]) -> Dict[str, DayBar]:
        """Today's open/high/low from the same OHLC endpoint.

        Dhan's OHLC block reports today's open/high/low alongside the previous
        session's close, so this is the REST-fallback source of the day range.
        Volume is not in that response and stays unknown.

        Written out rather than routed through ``_by_symbol``, which coerces
        every value to a positive float - the right guard for a price, the
        wrong one for a nested block.
        """
        raw = self._post_marketfeed("ohlc", refs)
        by_id = {str(r.provider_id): r.symbol for r in refs}

        bars: Dict[str, DayBar] = {}
        for security_id, entry in (raw or {}).items():
            symbol = by_id.get(str(security_id))
            if symbol is None or not isinstance(entry, dict):
                continue
            ohlc = entry.get("ohlc")
            if not isinstance(ohlc, dict):
                continue
            bars[symbol] = DayBar(
                open=_positive(ohlc.get("open")),
                high=_positive(ohlc.get("high")),
                low=_positive(ohlc.get("low")),
            )
        return bars

    def open_feed(self, refs: List[InstrumentRef]) -> FeedHandle:
        return DhanFeedHandle(self._token, self._client_id, refs).start()
