"""INDmoney (INDstocks API) market-data provider.

Calls the documented REST and WebSocket APIs directly - there is no SDK
dependency, and ``requests`` + ``websockets`` are already installed.

References (INDstocks API v1, docs/indstocks-api-docs.md):
  - Instrument ids : read from data/indmoney_instruments.json, generated by
                     scripts/fetch_indmoney_instruments.py - never downloaded here
  - Quotes         : GET https://api.indstocks.com/market/quotes/{ltp,full}
  - Daily candles  : GET https://api.indstocks.com/market/historical/1day
  - Live feed      : wss://ws-prices.indstocks.com/api/v1/ws/prices

Credentials: ``IND_MONEY_ACCESS_TOKEN`` only, sent raw (no ``Bearer``) in the
``Authorization`` header. It lasts 24h. Never logged.

Behaviour verified against the live API on 2026-09-25, where the published
docs are silent or wrong (details in docs/api/INDMONEY_API.md):

* Index quotes need the ``NIDX_`` prefix on REST and ``NIDX:`` on the socket,
  with the ids from the index instrument file (``40000001`` = Nifty 50). The
  docs' socket example ``NIDX:26000`` is silently ignored.
* Socket frames are **double-encoded** - a JSON string whose contents are JSON.
* Quote-mode ``close`` is the *live* price (identical to LTP-mode ``ltp`` tick
  for tick), not the previous close. So one quote subscription carries the
  price and the day's open/high/low/volume. No previous close is pushed.
* A single unknown scrip code fails the whole REST batch with HTTP 400, and
  the first batched call can come back with only some of the codes - so
  reference-data calls retry once for whatever was missing.
"""

import asyncio
import base64
import json
import logging
import os
import threading
import time
from datetime import date, datetime, time as dtime, timedelta
from typing import Dict, List, Optional, Tuple

import requests

from market.instruments import (
    INDMONEY_INSTRUMENTS_PATH,
    INDMONEY_SCRIPT,
    load_instruments,
    regenerate_hint,
)
from market.market_hours import IST, now_ist, todays_session_date
from market.providers.base import (
    SEGMENT_CASH,
    SEGMENT_INDEX,
    DayBar,
    FeedHandle,
    InstrumentRef,
    MarketDataProvider,
)
from market.providers.candles import positive, prior_close_from_candles

logger = logging.getLogger(__name__)

REST_BASE = "https://api.indstocks.com"
FEED_URL = "wss://ws-prices.indstocks.com/api/v1/ws/prices"
TOKEN_ENV = "IND_MONEY_ACCESS_TOKEN"
TOKEN_PAGE = "https://www.indstocks.com/app/api-trading/access-tokens"

#: Universe segment -> (REST prefix, socket prefix).
SEGMENT_PREFIXES = {
    SEGMENT_CASH: ("NSE", "NSE"),
    SEGMENT_INDEX: ("NIDX", "NIDX"),
}


def _prefixes(segment: str) -> Tuple[str, str]:
    return SEGMENT_PREFIXES.get((segment or SEGMENT_CASH).upper(), ("NSE", "NSE"))


def rest_code(ref: InstrumentRef) -> str:
    """``NSE_2885`` / ``NIDX_40000001`` - the REST ``scrip-codes`` form."""
    return f"{_prefixes(ref.segment)[0]}_{ref.provider_id}"


def feed_code(ref: InstrumentRef) -> str:
    """``NSE:2885`` / ``NIDX:40000001`` - the websocket form."""
    return f"{_prefixes(ref.segment)[1]}:{ref.provider_id}"


#: Quote endpoints take up to 1000 codes; historical takes at most 5.
REST_BATCH = 1000
HISTORY_BATCH = 5
SUBSCRIBE_BATCH = 500

#: INDmoney allows 5 requests/second in both the Quote and the Data (historical)
#: buckets. 4/s leaves headroom. Module level because the limit is per user and
#: the dashboard runs one provider instance per board.
MIN_REQUEST_INTERVAL = 0.25
_GATES = {"quote": threading.Lock(), "data": threading.Lock()}
_LAST_AT = {"quote": 0.0, "data": 0.0}


def _gate(bucket: str) -> None:
    """Block until it is safe to issue another request in ``bucket``."""
    with _GATES[bucket]:
        wait = MIN_REQUEST_INTERVAL - (time.monotonic() - _LAST_AT[bucket])
        if wait > 0:
            time.sleep(wait)
        _LAST_AT[bucket] = time.monotonic()


#: Calendar days of daily candles requested for a previous close. Only the last
#: two sessions matter; the rest is slack for weekends and holidays.
HISTORY_LOOKBACK_DAYS = 20


def _ist_midnight_ms(day: date) -> int:
    """Epoch milliseconds of 00:00 IST on ``day`` - the unit INDmoney's windows use."""
    return int(datetime.combine(day, dtime.min, IST).timestamp()) * 1000


def token_expiry(access_token: str) -> Optional[int]:
    """Unix expiry of an INDmoney access token (a JWT), or None if unreadable.

    Decoded, never verified - we are not the issuer - and never logged.
    """
    try:
        payload = (access_token or "").split(".")[1]
        payload += "=" * (-len(payload) % 4)
        expiry = json.loads(base64.urlsafe_b64decode(payload)).get("exp")
        return int(expiry) if expiry is not None else None
    except Exception:
        return None


def error_of(status_code: int, payload) -> Optional[str]:
    """Human-readable reason for a failed INDmoney response, or None if it succeeded.

    INDmoney uses at least four error shapes (see the Error Bucket page), so
    this reads whichever of ``error_type``/``debug_info``/``message``/``error``
    is present rather than branching on one.
    """
    body = payload if isinstance(payload, dict) else {}
    failed = (
        status_code >= 400
        or str(body.get("status", "")).lower() == "error"
        or body.get("success") is False
    )
    if not failed:
        return None
    parts = [
        str(body[key])
        for key in ("error_type", "message", "debug_info", "error")
        if body.get(key)
    ]
    return f"HTTP {status_code}: " + (" - ".join(parts) if parts else "no error detail")


def decode_frame(message) -> Optional[dict]:
    """One websocket frame as a dict, or None for anything that is not a tick.

    Frames arrive double-encoded; a single-encoded one is accepted too, in
    case INDmoney fixes that. Heartbeats and other non-JSON noise yield None.
    """
    if isinstance(message, (bytes, bytearray)):
        try:
            message = message.decode("utf-8")
        except UnicodeDecodeError:
            return None
    for _ in range(2):
        if isinstance(message, dict):
            return message
        if not isinstance(message, str):
            return None
        try:
            message = json.loads(message)
        except ValueError:
            return None
    return message if isinstance(message, dict) else None


def candles_to_series(candles) -> dict:
    """INDmoney ``[{ts, o, h, l, c, v}, ...]`` -> the shared parallel-array shape."""
    closes, stamps = [], []
    for candle in candles or []:
        if isinstance(candle, dict):
            closes.append(candle.get("c"))
            stamps.append(candle.get("ts"))
    return {"close": closes, "timestamp": stamps}


class IndMoneyFeedHandle(FeedHandle):
    """One INDmoney price websocket, driven on its own daemon thread.

    Subscribes in ``quote`` mode, whose ``close`` field is the live price (see
    the module docstring), so each tick yields both the LTP and the day bar.
    """

    def __init__(self, access_token: str, refs: List[InstrumentRef]):
        self._token = access_token
        self._refs = list(refs)
        # Frames name the instrument by bare id, without a segment. That is
        # unambiguous because each board is one segment with its own feed.
        self._by_id: Dict[str, str] = {str(r.provider_id): r.symbol for r in self._refs}

        self._lock = threading.Lock()
        self._prices: Dict[str, float] = {}
        self._bars: Dict[str, DayBar] = {}

        self._stop = threading.Event()
        self._ready = threading.Event()
        self._error: Optional[BaseException] = None
        self._alive = False
        self._thread = threading.Thread(target=self._run, name="indmoney-feed", daemon=True)

    # -- lifecycle ------------------------------------------------------
    def start(self, timeout: float = 20.0) -> "IndMoneyFeedHandle":
        """Start the socket and block until subscribed (or raise)."""
        self._thread.start()
        if not self._ready.wait(timeout):
            self.close()
            raise TimeoutError(f"INDmoney feed did not connect within {timeout:.0f}s")
        if self._error is not None:
            raise self._error
        return self

    @property
    def is_alive(self) -> bool:
        return self._alive and self._thread.is_alive() and not self._stop.is_set()

    def latest_prices(self) -> Dict[str, float]:
        with self._lock:
            return dict(self._prices)

    def day_bars(self) -> Dict[str, DayBar]:
        with self._lock:
            return dict(self._bars)

    def close(self) -> None:
        self._stop.set()
        self._alive = False

    # -- socket ---------------------------------------------------------
    def _run(self) -> None:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            loop.run_until_complete(self._main())
        except BaseException as e:  # noqa: BLE001 - surfaced via start()/is_alive
            self._error = e
            logger.warning("INDmoney feed stopped: %s: %s", type(e).__name__, e)
        finally:
            self._alive = False
            self._ready.set()
            try:
                loop.close()
            except Exception:
                pass

    @staticmethod
    def _connect(url: str, headers: Dict[str, str]):
        """``websockets.connect`` across the header-argument rename in v14."""
        try:
            from websockets.asyncio.client import connect

            return connect(url, additional_headers=headers, max_size=None, close_timeout=5)
        except ImportError:  # websockets < 13
            import websockets

            return websockets.connect(url, extra_headers=headers, max_size=None, close_timeout=5)

    async def _main(self) -> None:
        # The library's default client ping (every 20s) covers INDmoney's
        # advice to ping at least every 30s.
        async with self._connect(FEED_URL, {"Authorization": self._token}) as ws:
            for i in range(0, len(self._refs), SUBSCRIBE_BATCH):
                batch = self._refs[i : i + SUBSCRIBE_BATCH]
                await ws.send(
                    json.dumps(
                        {
                            "action": "subscribe",
                            "mode": "quote",
                            "instruments": [feed_code(r) for r in batch],
                        }
                    )
                )
            self._alive = True
            self._ready.set()
            logger.info("INDmoney feed connected - subscribed to %d instruments", len(self._refs))
            while not self._stop.is_set():
                try:
                    message = await asyncio.wait_for(ws.recv(), timeout=1.0)
                except asyncio.TimeoutError:
                    continue
                self._parse(message)

    def _parse(self, message) -> None:
        frame = decode_frame(message)
        if frame is None or frame.get("mode") not in ("quote", "ltp"):
            return
        symbol = self._by_id.get(str(frame.get("instrument")))
        data = frame.get("data")
        if symbol is None or not isinstance(data, dict):
            return

        if frame["mode"] == "ltp":
            price = positive(data.get("ltp"))
            bar = None
        else:
            price = positive(data.get("close"))
            volume = positive(data.get("volume"))
            # Index volume is always 0 - "unknown", not "nothing traded".
            bar = DayBar(
                open=positive(data.get("open")),
                high=positive(data.get("high")),
                low=positive(data.get("low")),
                volume=int(volume) if volume else None,
            )
        with self._lock:
            if price is not None:
                self._prices[symbol] = price
            if bar is not None:
                self._bars[symbol] = bar


class IndMoneyProvider(MarketDataProvider):
    """INDmoney provider: generated instrument file, REST quotes, live feed."""

    name = "indmoney"
    label = "INDmoney"

    def __init__(self, access_token: Optional[str] = None, timeout: int = 15):
        self._token = (access_token or os.getenv(TOKEN_ENV) or "").strip()
        self._timeout = timeout
        self._instrument_file = None

    # -- config / auth --------------------------------------------------
    def is_configured(self) -> bool:
        return bool(self._token) and not self._token.lower().startswith(("your_", "<"))

    def _headers(self) -> Dict[str, str]:
        return {"Authorization": self._token, "Accept": "application/json"}

    def _get(self, path: str, params: dict, bucket: str) -> Tuple[int, dict]:
        """One throttled GET, retried once on a 429. Returns (status, body)."""
        response = None
        for attempt in range(2):
            _gate(bucket)
            response = requests.get(
                f"{REST_BASE}{path}", headers=self._headers(), params=params, timeout=self._timeout
            )
            if response.status_code != 429:
                break
            if attempt == 0:
                logger.debug("INDmoney %s rate limited - retrying", path)
                time.sleep(1.0)
        try:
            body = response.json()
        except ValueError:
            body = {}
        return response.status_code, body if isinstance(body, dict) else {}

    def connect(self) -> None:
        if not self.is_configured():
            raise RuntimeError(f"INDmoney credentials missing - set {TOKEN_ENV}")
        expiry = token_expiry(self._token)
        if expiry is not None:
            remaining = expiry - int(time.time())
            if remaining <= 0:
                raise RuntimeError(
                    f"INDmoney access token has expired - generate a new one at {TOKEN_PAGE}"
                )
            logger.info("INDmoney access token valid for %.1f more hours", remaining / 3600)

        response = requests.get(
            f"{REST_BASE}/user/profile", headers=self._headers(), timeout=self._timeout
        )
        try:
            profile = response.json()
        except ValueError:
            profile = {}
        error = error_of(response.status_code, profile)
        if error:
            raise RuntimeError(
                f"INDmoney authentication failed ({error}). Regenerate the token at {TOKEN_PAGE}"
            )
        user = (profile.get("data") or {}).get("user_id", "")
        logger.info("INDmoney authenticated (user %s...)", str(user)[:4])

        # Quotes are free on INDmoney, but probe anyway so a token that
        # authenticates yet cannot read market data fails here, loudly.
        status, body = self._get("/market/quotes/ltp", {"scrip-codes": "NSE_2885"}, "quote")
        error = error_of(status, body)
        if error:
            raise RuntimeError(f"INDmoney market data unavailable: {error}")

    # -- reference data -------------------------------------------------
    def _instrument_set(self):
        """The generated instrument-id file, read once per provider."""
        if self._instrument_file is None:
            path = os.getenv("PULSE_INDMONEY_INSTRUMENTS_FILE") or INDMONEY_INSTRUMENTS_PATH
            self._instrument_file = load_instruments(path, script=INDMONEY_SCRIPT)
            if self._instrument_file.is_usable:
                logger.info("INDmoney instruments: %s", self._instrument_file.describe())
        return self._instrument_file

    def resolve_instruments(
        self, symbols: List[str], segment: str = SEGMENT_CASH
    ) -> Tuple[Dict[str, InstrumentRef], List[str]]:
        resolved: Dict[str, InstrumentRef] = {}
        missing: List[str] = []
        if not symbols:
            return resolved, missing

        segment = (segment or SEGMENT_CASH).upper()
        available = self._instrument_set()
        if not available.is_usable:
            logger.error("INDmoney instrument ids unavailable: %s", available.error)
            return resolved, list(symbols)

        lookup = available.security_ids(segment)
        for symbol in symbols:
            security_id = lookup.get(symbol)
            if not security_id:
                missing.append(symbol)
                continue
            resolved[symbol] = InstrumentRef(symbol=symbol, provider_id=security_id, segment=segment)

        logger.info("INDmoney resolved %d/%d instruments (%s)", len(resolved), len(symbols), segment)
        if missing:
            logger.warning(
                "%d symbol(s) missing from %s: %s. %s",
                len(missing),
                available.path,
                ", ".join(missing),
                regenerate_hint(available.path, INDMONEY_SCRIPT),
            )
        return resolved, missing

    def _quotes(self, endpoint: str, refs: List[InstrumentRef]) -> Dict[str, dict]:
        """Batched quote call. Returns ``{symbol: entry}``."""
        by_code = {rest_code(r): r.symbol for r in refs}
        codes = list(by_code)
        out: Dict[str, dict] = {}
        for i in range(0, len(codes), REST_BATCH):
            chunk = codes[i : i + REST_BATCH]
            status, body = self._get(
                f"/market/quotes/{endpoint}", {"scrip-codes": ",".join(chunk)}, "quote"
            )
            error = error_of(status, body)
            if error:
                logger.warning("INDmoney %s quote error: %s", endpoint, error)
                continue
            for code, entry in (body.get("data") or {}).items():
                symbol = by_code.get(code)
                if symbol is not None and isinstance(entry, dict):
                    out[symbol] = entry
        return out

    def _quotes_complete(self, endpoint: str, refs: List[InstrumentRef]) -> Dict[str, dict]:
        """``_quotes``, asking once more for anything the first answer left out.

        Used for reference data only: the first batched call of a session has
        been seen to return a subset of the codes it was asked for.
        """
        entries = self._quotes(endpoint, refs)
        gaps = [r for r in refs if r.symbol not in entries]
        if gaps and entries:
            entries.update(self._quotes(endpoint, gaps))
        return entries

    def get_previous_close(self, refs: List[InstrumentRef]) -> Dict[str, float]:
        """Previous close from the full-quote endpoint's ``prev_close``.

        The service only calls this while the market is open or pre-open;
        outside the session it uses ``get_prior_session_close`` instead.
        """
        entries = self._quotes_complete("full", refs)
        closes = {}
        for symbol, entry in entries.items():
            close = positive(entry.get("prev_close"))
            if close:
                closes[symbol] = close
        logger.info("INDmoney resolved previous close for %d/%d", len(closes), len(refs))
        return closes

    def get_prior_session_close(self, refs: List[InstrumentRef]) -> Dict[str, float]:
        """Previous close from daily candles, five instruments per request."""
        if not refs:
            return {}
        today = now_ist().date()
        window = {
            "start_time": _ist_midnight_ms(today - timedelta(days=HISTORY_LOOKBACK_DAYS)),
            # end_time is exclusive, so ask past today to include today's candle.
            "end_time": _ist_midnight_ms(today + timedelta(days=1)),
        }
        session_date = todays_session_date()

        by_code = {rest_code(r): r.symbol for r in refs}
        codes = list(by_code)
        closes: Dict[str, float] = {}
        failed_batches = 0
        for i in range(0, len(codes), HISTORY_BATCH):
            chunk = codes[i : i + HISTORY_BATCH]
            try:
                status, body = self._get(
                    "/market/historical/1day", {"scrip-codes": ",".join(chunk), **window}, "data"
                )
            except requests.RequestException as e:
                logger.debug("INDmoney historical request failed: %s", e)
                status, body = 0, {}
            error = error_of(status, body) if status else "request failed"
            if error:
                failed_batches += 1
                logger.debug("INDmoney historical error: %s", error)
                if failed_batches >= 2 and not closes:
                    logger.warning("INDmoney daily candles unavailable - abandoning the lookup")
                    break
                continue
            for code, block in (body.get("data") or {}).items():
                symbol = by_code.get(code)
                if symbol is None or not isinstance(block, dict):
                    continue
                close = prior_close_from_candles(candles_to_series(block.get("candles")), session_date)
                if close:
                    closes[symbol] = close

        logger.info("INDmoney resolved previous close for %d/%d from daily candles", len(closes), len(refs))
        return closes

    def get_ltp_snapshot(self, refs: List[InstrumentRef]) -> Dict[str, float]:
        prices = {}
        for symbol, entry in self._quotes("ltp", refs).items():
            price = positive(entry.get("live_price"))
            if price:
                prices[symbol] = price
        return prices

    def get_day_bars(self, refs: List[InstrumentRef]) -> Dict[str, DayBar]:
        """Today's open/high/low/volume from the full-quote endpoint."""
        bars: Dict[str, DayBar] = {}
        for symbol, entry in self._quotes("full", refs).items():
            volume = positive(entry.get("volume"))
            bars[symbol] = DayBar(
                open=positive(entry.get("day_open")),
                high=positive(entry.get("day_high")),
                low=positive(entry.get("day_low")),
                volume=int(volume) if volume else None,
            )
        return bars

    def open_feed(self, refs: List[InstrumentRef]) -> FeedHandle:
        return IndMoneyFeedHandle(self._token, refs).start()
