"""Zerodha Kite Connect market-data provider.

Calls the documented REST and WebSocket APIs directly - no ``kiteconnect``
SDK. The SDK's ``KiteTicker`` runs on Twisted, whose reactor cannot be
restarted within a process, and this service reconnects feeds as a matter of
course. ``requests`` + ``websockets`` (already installed) cover everything, as
they do for Dhan and INDmoney.

References (Kite Connect v3, https://kite.trade/docs/connect/v3/):
  - Login / token   : market/providers/kite_session.py, scripts/kite_login.py
  - Instrument ids  : read from data/kite_instruments.json, generated by
                      scripts/fetch_kite_instruments.py - never downloaded here
  - Quotes          : GET https://api.kite.trade/quote{,/ohlc,/ltp}?i=NSE:INFY
  - Daily candles   : GET https://api.kite.trade/instruments/historical/{token}/day
  - Live feed       : wss://ws.kite.trade?api_key=...&access_token=...

Kite identifies an instrument two ways, and each API uses one of them:
REST quotes are keyed by ``NSE:<tradingsymbol>`` (``NSE:NIFTY BANK``), while
the websocket and historical candles use the numeric ``instrument_token``. The
instrument file carries both; ``InstrumentRef.provider_id`` is the token.

Market data needs the paid Kite Connect plan; the free "Personal" plan has
orders and portfolio only. ``connect()`` probes a quote so a key without the
data plan fails there, loudly, instead of producing an empty board.

Read-only by construction: this module calls no order, GTT, alert or
portfolio-mutating endpoint, and the tests assert that.
"""

import asyncio
import json
import logging
import os
import struct
import threading
import time
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple

import requests

from market.instruments import (
    KITE_INSTRUMENTS_PATH,
    KITE_SCRIPT,
    load_instruments,
    regenerate_hint,
)
from market.market_hours import now_ist, todays_session_date
from market.providers.base import (
    SEGMENT_CASH,
    SEGMENT_INDEX,
    DayBar,
    FeedHandle,
    InstrumentRef,
    MarketDataProvider,
)
from market.providers.candles import positive, prior_close_from_candles
from market.providers.kite_session import (
    ACCESS_TOKEN_ENV,
    API_KEY_ENVS,
    API_ROOT,
    DEVELOPER_CONSOLE,
    KITE_VERSION,
    LOGIN_SCRIPT,
    api_key_from_env,
    error_of,
    load_session,
)

logger = logging.getLogger(__name__)

FEED_URL = "wss://ws.kite.trade"

#: Documented per-call instrument limits.
QUOTE_BATCH = 500  # /quote
OHLC_BATCH = 1000  # /quote/ohlc, /quote/ltp
SUBSCRIBE_BATCH = 3000  # per websocket connection

#: Documented rate limits: quotes 1 req/s, historical 3 req/s. Module level
#: because the limit is per API key and the dashboard runs one provider per board.
MIN_INTERVAL = {"quote": 1.05, "historical": 0.35}
_GATES = {bucket: threading.Lock() for bucket in MIN_INTERVAL}
_LAST_AT = {bucket: 0.0 for bucket in MIN_INTERVAL}


def _gate(bucket: str) -> None:
    """Block until it is safe to issue another request in ``bucket``."""
    with _GATES[bucket]:
        wait = MIN_INTERVAL[bucket] - (time.monotonic() - _LAST_AT[bucket])
        if wait > 0:
            time.sleep(wait)
        _LAST_AT[bucket] = time.monotonic()


#: Calendar days of daily candles requested for a previous close. Only the last
#: two sessions matter; the rest is slack for weekends and holidays.
HISTORY_LOOKBACK_DAYS = 20


def quote_key(tradingsymbol: str, exchange: str = "NSE") -> str:
    """``NSE:INFY`` / ``NSE:NIFTY BANK`` - the REST ``i=`` form."""
    return f"{exchange}:{tradingsymbol}"


def candles_to_series(candles) -> dict:
    """Kite ``[[iso_ts, o, h, l, c, v], ...]`` -> the shared parallel-array shape.

    Kite stamps daily candles ``2026-09-24T00:00:00+0530``; the shared helper
    wants epoch seconds. An unreadable stamp becomes None, which the helper
    treats as "date unknown" rather than a date.
    """
    closes, stamps = [], []
    for candle in candles or []:
        if not isinstance(candle, (list, tuple)) or len(candle) < 5:
            continue
        closes.append(candle[4])
        try:
            stamps.append(int(datetime.strptime(str(candle[0]), "%Y-%m-%dT%H:%M:%S%z").timestamp()))
        except (TypeError, ValueError):
            stamps.append(None)
    return {"close": closes, "timestamp": stamps}


# -- binary feed -------------------------------------------------------------

#: Low byte of an instrument_token is the exchange segment; 9 is indices.
SEGMENT_INDICES = 9
#: Currency segments quote in 1e-7 rupees; everything this dashboard uses is paise.
CURRENCY_SEGMENTS = {3: 10_000_000.0, 6: 10_000.0}

LTP_PACKET = 8
INDEX_QUOTE_PACKET = 28
INDEX_FULL_PACKET = 32
QUOTE_PACKET = 44
FULL_PACKET = 184


def split_packets(message: bytes) -> List[bytes]:
    """One binary frame -> its quote packets.

    Layout: ``int16`` packet count, then per packet an ``int16`` length and
    that many bytes. Big-endian throughout. A truncated frame yields the
    packets that were complete rather than raising.
    """
    if not isinstance(message, (bytes, bytearray)) or len(message) < 2:
        return []  # a 1-byte frame is Kite's heartbeat
    (count,) = struct.unpack(">H", message[0:2])
    packets, offset = [], 2
    for _ in range(count):
        if offset + 2 > len(message):
            break
        (length,) = struct.unpack(">H", message[offset : offset + 2])
        offset += 2
        if offset + length > len(message):
            break
        packets.append(bytes(message[offset : offset + length]))
        offset += length
    return packets


def parse_packet(packet: bytes) -> Optional[dict]:
    """One quote packet -> ``{token, ltp, open, high, low, close, volume}``.

    ``close`` is the *previous* session's close - pykiteconnect computes the
    day's change against it - and is None when the packet does not carry it.
    Prices are None when zero, the feed's value for "no trade yet".
    """
    size = len(packet)
    if size < LTP_PACKET:
        return None
    token, raw_ltp = struct.unpack(">II", packet[0:8])
    divisor = CURRENCY_SEGMENTS.get(token & 0xFF, 100.0)

    def price(raw: int) -> Optional[float]:
        return positive(raw / divisor)

    out = {"token": token, "ltp": price(raw_ltp), "open": None, "high": None,
           "low": None, "close": None, "volume": None}

    if (token & 0xFF) == SEGMENT_INDICES and size in (INDEX_QUOTE_PACKET, INDEX_FULL_PACKET):
        high, low, open_, close = struct.unpack(">IIII", packet[8:24])
        out.update(high=price(high), low=price(low), open=price(open_), close=price(close))
    elif size >= QUOTE_PACKET:
        volume, _buy, _sell, open_, high, low, close = struct.unpack(">IIIIIII", packet[16:44])
        out.update(open=price(open_), high=price(high), low=price(low), close=price(close),
                   volume=volume or None)
    return out


class KiteFeedHandle(FeedHandle):
    """One Kite ticker websocket, in ``quote`` mode, on its own daemon thread.

    Quote mode is enough: it carries LTP, the day's open/high/low/volume and
    the previous close. Full mode adds only market depth.
    """

    def __init__(self, api_key: str, access_token: str, refs: List[InstrumentRef]):
        self._api_key = api_key
        self._token = access_token
        self._refs = list(refs)
        self._by_token: Dict[int, str] = {}
        for ref in self._refs:
            try:
                self._by_token[int(ref.provider_id)] = ref.symbol
            except (TypeError, ValueError):
                logger.warning("Kite: %s has a non-numeric instrument token %r", ref.symbol, ref.provider_id)

        self._lock = threading.Lock()
        self._prices: Dict[str, float] = {}
        self._closes: Dict[str, float] = {}
        self._bars: Dict[str, DayBar] = {}

        self._stop = threading.Event()
        self._ready = threading.Event()
        self._error: Optional[BaseException] = None
        self._alive = False
        self._thread = threading.Thread(target=self._run, name="kite-feed", daemon=True)

    # -- lifecycle ------------------------------------------------------
    def start(self, timeout: float = 20.0) -> "KiteFeedHandle":
        """Start the socket and block until subscribed (or raise)."""
        self._thread.start()
        if not self._ready.wait(timeout):
            self.close()
            raise TimeoutError(f"Kite feed did not connect within {timeout:.0f}s")
        if self._error is not None:
            raise self._error
        return self

    @property
    def is_alive(self) -> bool:
        return self._alive and self._thread.is_alive() and not self._stop.is_set()

    def latest_prices(self) -> Dict[str, float]:
        with self._lock:
            return dict(self._prices)

    def previous_closes(self) -> Dict[str, float]:
        with self._lock:
            return dict(self._closes)

    def day_bars(self) -> Dict[str, DayBar]:
        with self._lock:
            return dict(self._bars)

    def close(self) -> None:
        self._stop.set()
        self._alive = False

    # -- socket ---------------------------------------------------------
    def _run(self) -> None:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            loop.run_until_complete(self._main())
        except BaseException as e:  # noqa: BLE001 - surfaced via start()/is_alive
            self._error = e
            logger.warning("Kite feed stopped: %s: %s", type(e).__name__, e)
        finally:
            self._alive = False
            self._ready.set()
            try:
                loop.close()
            except Exception:
                pass

    def _url(self) -> str:
        from urllib.parse import urlencode

        return f"{FEED_URL}?{urlencode({'api_key': self._api_key, 'access_token': self._token})}"

    @staticmethod
    def _connect(url: str):
        try:
            from websockets.asyncio.client import connect

            return connect(url, max_size=None, close_timeout=5)
        except ImportError:  # websockets < 13
            import websockets

            return websockets.connect(url, max_size=None, close_timeout=5)

    async def _main(self) -> None:
        tokens = list(self._by_token)
        async with self._connect(self._url()) as ws:
            for i in range(0, len(tokens), SUBSCRIBE_BATCH):
                batch = tokens[i : i + SUBSCRIBE_BATCH]
                await ws.send(json.dumps({"a": "subscribe", "v": batch}))
                await ws.send(json.dumps({"a": "mode", "v": ["quote", batch]}))
            self._alive = True
            self._ready.set()
            logger.info("Kite feed connected - subscribed to %d instruments", len(tokens))
            while not self._stop.is_set():
                try:
                    message = await asyncio.wait_for(ws.recv(), timeout=1.0)
                except asyncio.TimeoutError:
                    continue
                self._handle(message)

    def _handle(self, message) -> None:
        if isinstance(message, str):
            # Text frames are postbacks, broker messages and errors - never prices.
            try:
                body = json.loads(message)
            except ValueError:
                return
            if isinstance(body, dict) and body.get("type") == "error":
                logger.warning("Kite feed error: %s", body.get("data"))
            return
        self._parse(message)

    def _parse(self, message: bytes) -> None:
        updates = []
        for packet in split_packets(message):
            tick = parse_packet(packet)
            if tick is None:
                continue
            symbol = self._by_token.get(tick["token"])
            if symbol is not None:
                updates.append((symbol, tick))
        if not updates:
            return
        with self._lock:
            for symbol, tick in updates:
                if tick["ltp"] is not None:
                    self._prices[symbol] = tick["ltp"]
                if tick["close"] is not None:
                    self._closes[symbol] = tick["close"]
                if tick["open"] is not None or tick["high"] is not None:
                    self._bars[symbol] = DayBar(
                        open=tick["open"], high=tick["high"], low=tick["low"], volume=tick["volume"]
                    )


class KiteProvider(MarketDataProvider):
    """Zerodha Kite provider: generated instrument file, REST quotes, live feed."""

    name = "kite"
    label = "Kite"

    def __init__(
        self,
        api_key: Optional[str] = None,
        access_token: Optional[str] = None,
        timeout: int = 15,
    ):
        self._api_key = (api_key or api_key_from_env()).strip()
        self._explicit_token = (access_token or os.getenv(ACCESS_TOKEN_ENV) or "").strip()
        self._token = ""
        self._timeout = timeout
        self._instrument_file = None
        #: (segment, symbol) -> Kite tradingsymbol, filled by resolve_instruments.
        self._tradingsymbols: Dict[Tuple[str, str], str] = {}

    # -- config / auth --------------------------------------------------
    def _access_token(self) -> str:
        """Explicit / env token first, else today's saved login. No network I/O."""
        if self._explicit_token:
            return self._explicit_token
        session = load_session(self._api_key)
        return session.access_token if session else ""

    def is_configured(self) -> bool:
        if not self._api_key:
            return False
        if not self._access_token():
            logger.info("Kite has an API key but no session for today - run 'python %s'", LOGIN_SCRIPT)
            return False
        return True

    def _headers(self) -> Dict[str, str]:
        return {
            "X-Kite-Version": KITE_VERSION,
            "Authorization": f"token {self._api_key}:{self._token}",
        }

    def _get(self, path: str, params, bucket: Optional[str] = None) -> Tuple[int, dict]:
        """One GET, throttled when ``bucket`` is given and retried once on a 429."""
        response = None
        for attempt in range(2):
            if bucket:
                _gate(bucket)
            response = requests.get(
                f"{API_ROOT}{path}", headers=self._headers(), params=params, timeout=self._timeout
            )
            if response.status_code != 429:
                break
            if attempt == 0:
                logger.debug("Kite %s rate limited - retrying", path)
                time.sleep(1.0)
        try:
            body = response.json()
        except ValueError:
            body = {}
        return response.status_code, body if isinstance(body, dict) else {}

    def connect(self) -> None:
        if not self._api_key:
            raise RuntimeError(f"Kite credentials missing - set {API_KEY_ENVS[0]} in .env")
        self._token = self._access_token()
        if not self._token:
            raise RuntimeError(f"No Kite session for today - run 'python {LOGIN_SCRIPT}'")

        status, body = self._get("/user/profile", None)
        error = error_of(status, body)
        if error:
            hint = (
                f"The access token has expired or was revoked - run 'python {LOGIN_SCRIPT}'"
                if status == 403
                else f"Check the app at {DEVELOPER_CONSOLE}"
            )
            raise RuntimeError(f"Kite authentication failed ({error}). {hint}")
        user = (body.get("data") or {}).get("user_id", "")
        logger.info("Kite authenticated (user %s...)", str(user)[:2])

        # Market data is a separate paid plan; find out now rather than at render.
        status, body = self._get("/quote/ltp", [("i", quote_key("RELIANCE"))], "quote")
        error = error_of(status, body)
        if error:
            raise RuntimeError(
                f"Kite market data unavailable ({error}). Quotes and the live feed "
                f"need the Kite Connect plan, not the free Personal plan - see {DEVELOPER_CONSOLE}"
            )

    # -- reference data -------------------------------------------------
    def _instrument_set(self):
        """The generated instrument-id file, read once per provider."""
        if self._instrument_file is None:
            path = os.getenv("PULSE_KITE_INSTRUMENTS_FILE") or KITE_INSTRUMENTS_PATH
            self._instrument_file = load_instruments(path, script=KITE_SCRIPT)
            if self._instrument_file.is_usable:
                logger.info("Kite instruments: %s", self._instrument_file.describe())
        return self._instrument_file

    def resolve_instruments(
        self, symbols: List[str], segment: str = SEGMENT_CASH
    ) -> Tuple[Dict[str, InstrumentRef], List[str]]:
        resolved: Dict[str, InstrumentRef] = {}
        missing: List[str] = []
        if not symbols:
            return resolved, missing

        segment = (segment or SEGMENT_CASH).upper()
        available = self._instrument_set()
        if not available.is_usable:
            logger.error("Kite instrument ids unavailable: %s", available.error)
            return resolved, list(symbols)

        rows = available.instruments.get(segment) or {}
        tokens = available.security_ids(segment)
        for symbol in symbols:
            token = tokens.get(symbol)
            if not token:
                missing.append(symbol)
                continue
            tradingsymbol = str((rows.get(symbol) or {}).get("tradingsymbol") or symbol)
            self._tradingsymbols[(segment, symbol)] = tradingsymbol
            resolved[symbol] = InstrumentRef(symbol=symbol, provider_id=token, segment=segment)

        logger.info("Kite resolved %d/%d instruments (%s)", len(resolved), len(symbols), segment)
        if missing:
            logger.warning(
                "%d symbol(s) missing from %s: %s. %s",
                len(missing),
                available.path,
                ", ".join(missing),
                regenerate_hint(available.path, KITE_SCRIPT),
            )
        return resolved, missing

    def _quote_key(self, ref: InstrumentRef) -> str:
        segment = (ref.segment or SEGMENT_CASH).upper()
        return quote_key(self._tradingsymbols.get((segment, ref.symbol), ref.symbol), ref.exchange or "NSE")

    def _quotes(self, endpoint: str, refs: List[InstrumentRef]) -> Dict[str, dict]:
        """Batched quote call (``""``, ``"ohlc"`` or ``"ltp"``). Returns ``{symbol: entry}``."""
        path = f"/quote/{endpoint}" if endpoint else "/quote"
        batch = QUOTE_BATCH if not endpoint else OHLC_BATCH
        by_key = {self._quote_key(r): r.symbol for r in refs}
        keys = list(by_key)
        out: Dict[str, dict] = {}
        for i in range(0, len(keys), batch):
            chunk = keys[i : i + batch]
            status, body = self._get(path, [("i", key) for key in chunk], "quote")
            error = error_of(status, body)
            if error:
                logger.warning("Kite %s error: %s", path, error)
                continue
            # Instruments with no data are simply absent from the response.
            for key, entry in (body.get("data") or {}).items():
                symbol = by_key.get(key)
                if symbol is not None and isinstance(entry, dict):
                    out[symbol] = entry
        return out

    def get_ohlc_quotes(self, refs: List[InstrumentRef]) -> Dict[str, dict]:
        """Raw ``/quote/ohlc`` entries (``last_price`` + ``ohlc``) per symbol.

        Up to 1000 instruments per request, so every F&O stock is one call.
        Used by the F&O movers dashboard for today's live moves.
        """
        return self._quotes("ohlc", refs)

    def get_previous_close(self, refs: List[InstrumentRef]) -> Dict[str, float]:
        """Previous close from ``/quote/ohlc``'s ``ohlc.close``.

        The service only calls this while the market is open or pre-open;
        outside the session it uses ``get_prior_session_close`` instead.
        """
        closes = {}
        for symbol, entry in self._quotes("ohlc", refs).items():
            close = positive((entry.get("ohlc") or {}).get("close"))
            if close:
                closes[symbol] = close
        logger.info("Kite resolved previous close for %d/%d", len(closes), len(refs))
        return closes

    def get_prior_session_close(self, refs: List[InstrumentRef]) -> Dict[str, float]:
        """Previous close from daily candles - one request per instrument, 3/s."""
        if not refs:
            return {}
        today = now_ist().date()
        window = {
            "from": f"{today - timedelta(days=HISTORY_LOOKBACK_DAYS)} 00:00:00",
            "to": f"{today} 23:59:59",
        }
        session_date = todays_session_date()

        closes: Dict[str, float] = {}
        failures = 0
        for ref in refs:
            try:
                status, body = self._get(
                    f"/instruments/historical/{ref.provider_id}/day", window, "historical"
                )
            except requests.RequestException as e:
                logger.debug("Kite historical request failed: %s", e)
                status, body = 0, {}
            error = error_of(status, body) if status else "request failed"
            if error:
                failures += 1
                logger.debug("Kite historical error for %s: %s", ref.symbol, error)
                if failures >= 3 and not closes:
                    logger.warning("Kite daily candles unavailable (%s) - abandoning the lookup", error)
                    break
                continue
            candles = (body.get("data") or {}).get("candles")
            close = prior_close_from_candles(candles_to_series(candles), session_date)
            if close:
                closes[ref.symbol] = close

        logger.info("Kite resolved previous close for %d/%d from daily candles", len(closes), len(refs))
        return closes

    def get_ltp_snapshot(self, refs: List[InstrumentRef]) -> Dict[str, float]:
        prices = {}
        for symbol, entry in self._quotes("ltp", refs).items():
            price = positive(entry.get("last_price"))
            if price:
                prices[symbol] = price
        return prices

    def get_day_bars(self, refs: List[InstrumentRef]) -> Dict[str, DayBar]:
        """Today's open/high/low/volume from the full ``/quote`` endpoint."""
        bars: Dict[str, DayBar] = {}
        for symbol, entry in self._quotes("", refs).items():
            ohlc = entry.get("ohlc") or {}
            volume = positive(entry.get("volume"))
            bars[symbol] = DayBar(
                open=positive(ohlc.get("open")),
                high=positive(ohlc.get("high")),
                low=positive(ohlc.get("low")),
                volume=int(volume) if volume else None,
            )
        return bars

    def open_feed(self, refs: List[InstrumentRef]) -> FeedHandle:
        if not self._token:
            self._token = self._access_token()
        return KiteFeedHandle(self._api_key, self._token, refs).start()
