"""Daily top gainers / losers for F&O stocks, from a stored close history.

Every broker answers "what did this stock close at on each day" only one
instrument per request, while "what is it at right now" is one bulk request for
up to 1000 instruments. So the daily closes are kept in a local file, built up
by ``scripts/update_fno_history.py``, and the dashboard reads it:

* past days come from the file - no API call at all;
* today, while the market is open, is one bulk quote on top.

Two files in ``data/``, both written only by that script:

``fno_universe.json``
    The stocks with NSE futures (from Kite's public NFO dump), each with its
    Kite ``instrument_token``. Changes when NSE adds or removes F&O stocks.
``fno_daily_closes.csv``
    Long format, one row per (date, symbol): ``date,symbol,open,high,low,
    close,volume``. Plain comma CSV so it opens in Excel with a double-click
    and diffs line by line in git. A year of ~210 stocks is ~2.5 MB.

A day's move is that day's close against the **previous stored close for the
same symbol**. That is only right if no trading day is missing in between, so
``daily_changes`` refuses to compute a move across a gap it can see (a symbol
absent on a day other symbols have) rather than presenting a two-day move as
one day's.

Nothing here talks to a broker; it is pure data handling and fully testable.
"""

import csv
import io
import json
import logging
import os
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Dict, Iterable, List, Optional, Tuple

logger = logging.getLogger(__name__)

UNIVERSE_PATH = os.path.join("data", "fno_universe.json")
CLOSES_PATH = os.path.join("data", "fno_daily_closes.csv")
UPDATE_SCRIPT = "scripts/update_fno_history.py"

CLOSE_COLUMNS = ("date", "symbol", "open", "high", "low", "close", "volume")


# -- universe ----------------------------------------------------------------


@dataclass
class FnoUniverse:
    """F&O stocks and their Kite instrument tokens."""

    #: symbol -> Kite instrument_token (as a string, like the other id files)
    tokens: Dict[str, str] = field(default_factory=dict)
    generated_at: Optional[datetime] = None
    path: str = ""
    error: str = ""

    @property
    def symbols(self) -> List[str]:
        return sorted(self.tokens)

    @property
    def is_usable(self) -> bool:
        return bool(self.tokens)


def fno_underlyings(nfo_csv: str) -> set:
    """Names that have a stock or index future in Kite's NFO dump."""
    names = set()
    for row in csv.DictReader(io.StringIO(nfo_csv)):
        if (row.get("instrument_type") or "").strip() == "FUT":
            name = (row.get("name") or "").strip()
            if name:
                names.add(name)
    return names


def nse_equity_tokens(nse_csv: str) -> Dict[str, str]:
    """``tradingsymbol -> instrument_token`` for NSE cash equities in Kite's NSE dump."""
    tokens: Dict[str, str] = {}
    for row in csv.DictReader(io.StringIO(nse_csv)):
        if (row.get("segment") or "").strip() != "NSE":
            continue
        if (row.get("instrument_type") or "").strip() != "EQ":
            continue
        symbol = (row.get("tradingsymbol") or "").strip()
        token = (row.get("instrument_token") or "").strip()
        if symbol and token:
            tokens.setdefault(symbol, token)
    return tokens


def build_universe(nfo_csv: str, nse_csv: str) -> Tuple[Dict[str, str], List[str]]:
    """F&O stocks with their cash-equity tokens, plus the F&O names not matched.

    Index futures (NIFTY, BANKNIFTY, ...) have no NSE equity row, so they drop
    out here by construction and show up in the unmatched list.
    """
    underlyings = fno_underlyings(nfo_csv)
    equities = nse_equity_tokens(nse_csv)
    tokens = {name: equities[name] for name in underlyings if name in equities}
    unmatched = sorted(underlyings - set(tokens))
    return tokens, unmatched


def save_universe(tokens: Dict[str, str], unmatched: List[str], path: str = UNIVERSE_PATH) -> None:
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": "https://api.kite.trade/instruments/NFO + /instruments/NSE",
        "note": (
            f"Generated by {UPDATE_SCRIPT}. Stocks with NSE futures and their "
            "Kite instrument_token. Unmatched names are index futures."
        ),
        "count": len(tokens),
        "unmatched": unmatched,
        "tokens": dict(sorted(tokens.items())),
    }
    _atomic_write(path, json.dumps(payload, indent=2, sort_keys=True) + "\n")


def load_universe(path: str = UNIVERSE_PATH) -> FnoUniverse:
    """Never raises - check ``is_usable`` and show ``error``."""
    if not os.path.exists(path):
        return FnoUniverse(path=path, error=f"No F&O universe at {path}. Run 'python {UPDATE_SCRIPT}'.")
    try:
        with open(path, encoding="utf-8") as handle:
            raw = json.load(handle)
        tokens = {str(k): str(v) for k, v in (raw.get("tokens") or {}).items() if v}
    except (OSError, ValueError, AttributeError) as exc:
        return FnoUniverse(path=path, error=f"Could not read {path}: {exc}")
    generated = None
    try:
        generated = datetime.fromisoformat(raw.get("generated_at") or "")
    except (TypeError, ValueError):
        pass
    if not tokens:
        return FnoUniverse(path=path, error=f"{path} lists no F&O stocks. Run 'python {UPDATE_SCRIPT}'.")
    return FnoUniverse(tokens=tokens, generated_at=generated, path=path)


# -- close history -----------------------------------------------------------


def _atomic_write(path: str, text: str) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    temp = f"{path}.tmp"
    with open(temp, "w", encoding="utf-8", newline="") as handle:
        handle.write(text)
    os.replace(temp, path)


def _number(value) -> Optional[float]:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if number > 0 else None


def load_closes(path: str = CLOSES_PATH) -> Dict[Tuple[str, str], dict]:
    """``{(date, symbol): row}``. Missing file -> empty. Bad rows are skipped."""
    rows: Dict[Tuple[str, str], dict] = {}
    if not os.path.exists(path):
        return rows
    with open(path, encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            day, symbol = (row.get("date") or "").strip(), (row.get("symbol") or "").strip()
            if day and symbol and _number(row.get("close")):
                rows[(day, symbol)] = {k: row.get(k, "") for k in CLOSE_COLUMNS}
    return rows


def upsert_closes(existing: Dict[Tuple[str, str], dict], new_rows: Iterable[dict]) -> int:
    """Add or replace rows keyed by (date, symbol). Returns how many changed."""
    changed = 0
    for row in new_rows:
        key = (str(row["date"]), str(row["symbol"]))
        clean = {k: ("" if row.get(k) is None else str(row.get(k))) for k in CLOSE_COLUMNS}
        if existing.get(key) != clean:
            existing[key] = clean
            changed += 1
    return changed


def save_closes(rows: Dict[Tuple[str, str], dict], path: str = CLOSES_PATH) -> None:
    """Rewrite the file sorted by date then symbol - stable, diff-friendly."""
    out = io.StringIO()
    writer = csv.DictWriter(out, fieldnames=CLOSE_COLUMNS, lineterminator="\n")
    writer.writeheader()
    for key in sorted(rows):
        writer.writerow(rows[key])
    _atomic_write(path, out.getvalue())


def candle_rows(symbol: str, candles, exclude_date: Optional[str] = None) -> List[dict]:
    """Kite daily candles ``[[iso_ts, o, h, l, c, v], ...]`` -> close-file rows.

    ``exclude_date`` drops that day's candle - used for today while the session
    is still open, because its "close" is only the current price.
    """
    rows = []
    for candle in candles or []:
        if not isinstance(candle, (list, tuple)) or len(candle) < 6:
            continue
        day = str(candle[0])[:10]
        if day == exclude_date or not _number(candle[4]):
            continue
        rows.append({
            "date": day, "symbol": symbol, "open": candle[1], "high": candle[2],
            "low": candle[3], "close": candle[4], "volume": candle[5],
        })
    return rows


# -- movers ------------------------------------------------------------------


@dataclass
class Move:
    symbol: str
    date: str
    close: float
    previous_close: float

    @property
    def change_pct(self) -> float:
        return (self.close - self.previous_close) / self.previous_close * 100.0


def trading_days(rows: Dict[Tuple[str, str], dict]) -> List[str]:
    """Dates present in the history, ascending."""
    return sorted({day for day, _ in rows})


def daily_changes(rows: Dict[Tuple[str, str], dict]) -> Dict[str, List[Move]]:
    """``{date: [Move, ...]}`` for every stored day that has a previous day.

    The previous close is the symbol's close on the **previous trading day in
    the file**. If the symbol has no row that day (suspension, a data gap),
    no move is reported for it rather than silently spanning two days.
    """
    days = trading_days(rows)
    closes: Dict[str, Dict[str, float]] = {}
    for (day, symbol), row in rows.items():
        closes.setdefault(day, {})[symbol] = _number(row.get("close"))
    moves: Dict[str, List[Move]] = {}
    for previous, day in zip(days, days[1:]):
        before = closes.get(previous, {})
        for symbol, close in closes.get(day, {}).items():
            prior = before.get(symbol)
            if close and prior:
                moves.setdefault(day, []).append(Move(symbol, day, close, prior))
    return moves


def live_moves(
    quotes: Dict[str, dict],
    today: str,
    stored: Dict[Tuple[str, str], dict],
    in_session: bool,
) -> List[Move]:
    """Today's moves from one bulk ``/quote/ohlc`` answer.

    During the session the quote's ``ohlc.close`` is the previous close
    (verified against daily candles on 2026-09-25). Outside it that field's
    meaning is not verified, so the last *stored* close before today is used
    instead, and a symbol without one is left out.
    """
    last_stored: Dict[str, Tuple[str, float]] = {}
    for (day, symbol), row in stored.items():
        close = _number(row.get("close"))
        if day < today and close and (symbol not in last_stored or day > last_stored[symbol][0]):
            last_stored[symbol] = (day, close)

    moves = []
    for symbol, entry in quotes.items():
        price = _number(entry.get("last_price"))
        if not price:
            continue
        previous = _number((entry.get("ohlc") or {}).get("close")) if in_session else None
        if previous is None and symbol in last_stored:
            previous = last_stored[symbol][1]
        if previous:
            moves.append(Move(symbol, today, price, previous))
    return moves


def top_movers(moves: List[Move], limit: int = 10, symbols: Optional[set] = None) -> Tuple[List[Move], List[Move]]:
    """``(gainers, losers)``, each best-first, optionally within ``symbols``.

    A day where everything fell still has "top gainers" - the smallest losers -
    so callers should show the sign rather than assume gainers are positive.
    """
    pool = [m for m in moves if symbols is None or m.symbol in symbols]
    ranked = sorted(pool, key=lambda m: (m.change_pct, m.symbol), reverse=True)
    gainers = ranked[:limit]
    losers = sorted(pool, key=lambda m: (m.change_pct, m.symbol))[:limit]
    return gainers, losers
